import { ShowType } from "../../sharedCopy";

export const show: ShowType = {
	rounds: [
		{
			players: [
				{
					displayName: "Eli",
					pronouns: "He/Him",
					score: 0,
					soundIndex: 0,
					isWinner: false,
				},
				{
					displayName: "Remy",
					pronouns: "He/Him",
					score: 0,
					soundIndex: 1,
					isWinner: false,
				},
				{
					displayName: "Shore",
					pronouns: "He/Him",
					score: 0,
					soundIndex: 2,
					isWinner: false,
				},
			],
			minigame: "Sexy Slogans",
			example: "Nike: Just Do Me",
			timelength: 15,
		},
		{
			players: [
				{
					displayName: "Rochelle",
					pronouns: "She/Her",
					score: 0,
					soundIndex: 3,
					isWinner: false,
				},
				{
					displayName: "Andy",
					pronouns: "He/Him",
					score: 0,
					soundIndex: 4,
					isWinner: false,
				},
				{
					displayName: "Clayton",
					pronouns: "He/Him",
					score: 0,
					soundIndex: 5,
					isWinner: false,
				},
			],
			minigame: "We've Got Movie Line",
			example:
				"Sex with me is like the movie Aladdin: the sequel will be nowhere near as good as the original.",
			timelength: 15,
		},
		{
			players: [
				{
					displayName: "Def",
					pronouns: "Any/All",
					score: 0,
					soundIndex: 6,
					isWinner: false,
				},
				{
					displayName: "Steven",
					pronouns: "He/Him",
					score: 0,
					soundIndex: 7,
					isWinner: false,
				},
				{
					displayName: "Bridjet",
					pronouns: "She/Her",
					score: 0,
					soundIndex: 8,
					isWinner: false,
				},
			],
			minigame: "Communication Breakdown",
			example: "Doing the laundry - you mean I have to put ANOTHER load in?",
			timelength: 15,
		},
		{
			players: [
				{
					displayName: "Dummy Data",
					pronouns: "",
					score: 0,
					soundIndex: 9,
					isWinner: false,
				},
				{
					displayName: "Dummy Data",
					pronouns: "",
					score: 0,
					soundIndex: 10,
					isWinner: false,
				},
				{
					displayName: "Dummy Data",
					pronouns: "",
					score: 0,
					soundIndex: 11,
					isWinner: false,
				},
			],
			minigame: "Bad Communication",
			example: "Doing the laundry - Yeah I'm OK to put another load in before going to bed.",
			timelength: 10,
		},
	],
	images: [
		"Apply.png",
		"Caroline.png",
		"Chris Heiberger.png",
		"Chris Kanner.png",
		"Elijah.png",
		"Indy.png",
		"Josh.png",
		"JD.png",
		"Justin.png",
		"Karissa.png",
		"Mark Hale.png",
		"Melissa.png",
		"Q.png",
		"Stephanie.png",
		"Tanya.png",
		"Adam.png",
		"Social.png",
	],
	logo: "logo.png",
	apply: "Apply.png",
	social: "Social.png",
};
